#!/usr/bash
MainDir="$(pwd)"
apt-ftparchive packages $MainDir/pool > $MainDir/dists/stable/main/binary-all/Packages
cd $MainDir/dists/stable/main/binary-all/
bzip2 -c9 Packages > Packages.bz2
xz -c9 Packages > Packages.xz
xz -5fkev --format=lzma Packages > Packages.lzma
lz4 -c9 Packages > Packages.lz4
gzip -c9 Packages > Packages.gz
zstd -c19 Packages > Packages.zst


# While we are at it, also generate Contents-all files
apt-ftparchive contents $MainDir/pool > $MainDir/dists/stable/main/Contents-all
cd $MainDir/dists/stable/main/
bzip2 -c9 Contents-all > Contents-all.bz2
xz -c9 Contents-all > Contents-all.xz
xz -5fkev --format=lzma Contents-all > Contents-all.lzma
lz4 -c9 Contents-all > Contents-all.lz4
gzip -c9 Contents-all > Contents-all.gz
zstd -c19 Contents-all > Contents-all.zst

cd ..

grep -E "Origin:|Label:|Suite:|Version:|Codename:|Architectures:|Components:|Description:" $MainDir/dists/stable/Release > Base
apt-ftparchive release . > Release
cat Base Release > out && mv out Release
cp Release InRelease

# This line below will ask for your password defined on step 2. Replace what's on <> with the right value, it should look like step 4.
gpg --pinentry-mode loopback -abs -u 92E1182CBA654770F764BC6A6A9597CDFCDAD454 -o Release.gpg Release
gpg --pinentry-mode loopback -abs -u 92E1182CBA654770F764BC6A6A9597CDFCDAD454 -o InRelease.gpg InRelease
